# Generated by Django 4.2.19 on 2025-02-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartelera", "0002_alter_archivedevent_access_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedevent",
            name="access_type",
            field=models.CharField(
                choices=[("f", "Free"), ("s", "Paid subscriptions only")],
                default="s",
                max_length=1,
                verbose_name="acceso al evento",
            ),
        ),
        migrations.AlterField(
            model_name="liveembedevent",
            name="access_type",
            field=models.CharField(
                choices=[("f", "Free"), ("s", "Paid subscriptions only")],
                default="s",
                max_length=1,
                verbose_name="acceso al evento",
            ),
        ),
    ]
