# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_auto_20210722_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'attachments', verbose_name='archivo')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripci\xf3n')),
                ('is_image', models.BooleanField(default=False, editable=False, verbose_name='es imagen')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaci\xf3n')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.Article', verbose_name='art\xedculo')),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
            },
        ),
    ]
