# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-01 00:57

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name=b'moneda')),
                ('slug', models.SlugField(unique=True, verbose_name=b'slug')),
                ('symbol', models.CharField(max_length=4, verbose_name=b's\xc3\xadmbolo')),
                ('flag', models.ImageField(blank=True, null=True, upload_to=exchange.models.flag_upload_to, verbose_name=b'bandera')),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('buy', models.FloatField(verbose_name='compra')),
                ('sale', models.FloatField(verbose_name='venta')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Currency')),
            ],
            options={
                'get_latest_by': 'date',
                'verbose_name': 'cotizaci\xf3n',
                'verbose_name_plural': 'cotizaciones',
            },
        ),
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set([('currency', 'date')]),
        ),
    ]
