# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='allow_news',
            field=models.BooleanField(default=True, verbose_name='acepta novedades'),
        ),
    ]
