# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0002_subscriber_allow_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='plan_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
