# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0003_auto_20210420_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='costumer_id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='days',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='contact_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='CRM id'),
        ),
    ]
