# Generated by Django 4.1.4 on 2023-08-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_article_sp_id'),
        ('thedaily', '0005_remove_subscription_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='category_newsletters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'has_newsletter': True}, to='core.category'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='newsletters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'has_newsletter': True}, to='core.publication'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='province',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='province',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('MO', 'Mensual'), ('Q', 'Trimestral'), ('BA', 'Semestral'), ('AN', 'Anual')], max_length=2, verbose_name='plan'),
        ),
    ]
