# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20221204_2346'),
        ('thedaily', '0005_remove_subscription_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='articles_bought',
            field=models.ManyToManyField(blank=True, to='core.Article'),
        ),
    ]
