# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0005_remove_subscription_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('PAP', 'Edición papel + Digital'), ('DIG', 'Digital (Edición web)')], default='DIG', max_length=3, verbose_name='suscripción'),
        ),
        migrations.AlterField(
            model_name='subscriptionprices',
            name='ga_category',
            field=models.CharField(blank=True, choices=[('D', 'Digital'), ('P', 'Papel')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprices',
            name='subscription_type',
            field=models.CharField(choices=[('DDIGM', 'Suscripción digital'), ('PAPYDIM', 'Suscripción papel')], default='PAPYDIM', max_length=7, unique=True, verbose_name='tipo'),
        ),
    ]
