# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20221025_1620'),
        ('thedaily', '0006_auto_20221023_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='articles_bought',
            field=models.ManyToManyField(blank=True, to='core.Article'),
        ),
    ]
