# Generated by Django 4.1.4 on 2023-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0006_alter_subscriber_category_newsletters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='document',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='documento de identidad'),
        ),
    ]
