# Generated by Django 4.1.4 on 2024-03-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0007_alter_subscriber_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='terms_and_conds_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
