# Generated by Django 4.1.4 on 2024-03-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0008_subscriber_terms_and_conds_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_articles', models.PositiveSmallIntegerField(unique=True)),
                ('template_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'remaining content',
                'verbose_name_plural': 'remaining contents',
            },
        ),
    ]
