# Generated by Django 4.1.4 on 2024-09-07 18:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0010_mailtrainlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="teléfono"
            ),
        ),
    ]
