# Generated by Django 4.1.4 on 2024-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0011_alter_subscriber_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthstate",
            name="phone_submitted_blank",
            field=models.BooleanField(default=False),
        ),
    ]
