# Generated by Django 4.1.13 on 2024-09-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0012_oauthstate_phone_submitted_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="ciudad de residencia",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="país de residencia"
            ),
        ),
    ]
