# Generated by Django 4.1.13 on 2024-11-08 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0013_alter_subscriber_city_alter_subscriber_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprices",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="descuento (%)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionprices",
            name="extra_info",
            field=models.JSONField(
                default=dict,
                help_text="Diccionario Python en formato JSON",
                verbose_name="información extra",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionprices",
            name="months",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="meses"),
        ),
        migrations.AddField(
            model_name="subscriptionprices",
            name="price_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="precio total",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="order",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="orden"),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="precio",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[],
                max_length=7,
                null=True,
                unique=True,
                verbose_name="tipo",
            ),
        ),
    ]
