# Generated by Django 4.1.13 on 2024-11-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0014_subscriptionprices_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="lento_pdf",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="name",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="ruta_fs",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="ruta_lento",
        ),
        migrations.AddField(
            model_name="subscriber",
            name="extra_info",
            field=models.JSONField(
                default=dict,
                help_text="Diccionario Python en formato JSON",
                verbose_name="información extra",
            ),
        ),
    ]
