# Generated by Django 4.1.13 on 2025-01-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "thedaily",
            "0015_remove_subscriber_lento_pdf_remove_subscriber_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="document_type",
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True),
        ),
    ]
