# Generated by Django 4.1.13 on 2025-01-15 23:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0016_subscriber_document_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "get_latest_by": "date_created",
                "ordering": ("-date_created",),
                "verbose_name": "suscripción",
                "verbose_name_plural": "suscripciones",
            },
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="document",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="email",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend1_email",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend1_name",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend1_telephone",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend2_email",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend2_name",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend2_telephone",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend3_email",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend3_name",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="friend3_telephone",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="observations",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="public_profile",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_end",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="telephone",
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="billing email"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_id_doc",
            field=models.CharField(
                max_length=31, null=True, verbose_name="billing identification document"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="billing name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="billing phone",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="next_billing",
            field=models.DateField(blank=True, null=True, verbose_name="next billing"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscriber_rename",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[],
                max_length=64,
                null=True,
                verbose_name="departamento",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscriber",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("PAP", "Edición papel + Digital"),
                    ("DIG", "Digital (Edición web)"),
                ],
                default="DIG",
                max_length=3,
                verbose_name="tipo de suscripción",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type_prices",
            field=models.ManyToManyField(
                blank=True, to="thedaily.subscriptionprices", verbose_name="productos"
            ),
        ),
        migrations.RunSQL(
            # Forward SQL (when migrating up)
            sql="""
                UPDATE thedaily_subscription, thedaily_subscriber s
                SET subscriber_rename = s.id
                WHERE s.user_id = subscriber;
            """,
            reverse_sql="""
                UPDATE thedaily_subscription, thedaily_subscriber s
                SET subscriber = s.user_id
                WHERE s.id = subscriber_rename;
            """,
        ),
    ]
