# Generated by Django 4.1.13 on 2025-01-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0017_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscriber",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscriber_rename",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="thedaily.subscriber",
            ),
        ),
    ]
