# Generated by Django 4.1.13 on 2025-01-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_articlerel_article_alter_articlerel_edition_and_more"),
        ("thedaily", "0019_rename_subscriber_rename_subscription_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprices",
            name="currency_id",
            field=models.CharField(
                blank=True,
                choices=[],
                default=None,
                max_length=3,
                null=True,
                verbose_name="moneda",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
                verbose_name="publicación",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[],
                max_length=31,
                null=True,
                unique=True,
                verbose_name="tipo",
            ),
        ),
    ]
