# Generated by Django 4.1.13 on 2025-01-23 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0020_subscriptionprices_currency_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="price_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="precio total",
            ),
            preserve_default=False,
        ),
    ]
