# Generated by Django 4.2.19 on 2025-04-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0021_subscription_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprices",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="subscription_type",
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
