# Generated by Django 4.2.19 on 2025-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0022_subscriptionprices_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprices",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="subscription_type",
            field=models.SlugField(default="", max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
