# Generated by Django 4.2.21 on 2025-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0023_alter_subscriptionprices_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthstate",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
