# Generated by Django 4.2.21 on 2025-08-01 17:59

from django.db import migrations, models
import django.db.models.deletion
import thedaily.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_alter_articlebodyimage_display"),
        ("thedaily", "0024_oauthstate_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprices",
            name="ga_category",
            field=models.CharField(
                blank=True,
                choices=[("D", "Digital"), ("P", "Papel")],
                default="D",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="orden"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprices",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                default=thedaily.models.default_price_publication_when_unique,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
                verbose_name="publicación",
            ),
        ),
    ]
