# Generated by Django 4.2.23 on 2025-08-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedaily", "0025_alter_subscriptionprices_ga_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
