# Generated by Django 4.1.4 on 2023-08-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[(0, 'email')], max_length=1, verbose_name='medium'),
        ),
    ]
