# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0003_adapt_max_tag_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('tags', models.ManyToManyField(blank=True, to='tagging.Tag')),
            ],
        ),
    ]
