# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'videologue', verbose_name=b'Video')),
                ('title', models.CharField(max_length=255, verbose_name=b'T\xc3\xadtulo')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name=b'Slug')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Pie')),
                ('byline', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Autor/es')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n')),
                ('date_uploaded', models.DateTimeField(blank=True, editable=False, null=True, verbose_name=b'Subido')),
                ('times_viewed', models.PositiveIntegerField(default=0, editable=False, verbose_name=b'Visto')),
                ('is_public', models.BooleanField(default=True, verbose_name=b'P\xc3\xbablico')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL de YouTube')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='T\xedtulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('yt_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='ID Youtube')),
            ],
            options={
                'get_latest_by': 'date_created',
                'verbose_name': 'Video YouTube',
                'verbose_name_plural': 'Videos YouTube',
            },
        ),
    ]
