# Generated by Django 4.1.4 on 2023-08-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videologue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='byline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor/es'),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pie'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Subido'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videologue', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='times_viewed',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Visto'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
