# Generated by Django 4.2.19 on 2025-02-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videologue", "0002_alter_video_byline_alter_video_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="date_uploaded",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Subido"
            ),
        ),
    ]
