# Generated by Django 4.2.19 on 2025-03-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videologue", "0003_alter_video_date_uploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubevideo",
            name="url",
            field=models.URLField(verbose_name="URL de YouTube"),
        ),
        migrations.AlterUniqueTogether(
            name="youtubevideo",
            unique_together={("url", "title")},
        ),
    ]
