# Generated by Django 4.1.4 on 2023-08-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerad',
            name='content',
            field=models.ImageField(help_text='Dimensiones: 970×250px</br>Tamaño máximo permitido: 150kb</br>Formato: JPG, GIF, PNG', upload_to='adzone/bannerads/', verbose_name='Banner escritorio'),
        ),
        migrations.AlterField(
            model_name='bannerad',
            name='mobile_content',
            field=models.ImageField(blank=True, help_text='Dimensiones: 300×250px</br>Tamaño máximo permitido: 150kb</br>Formato: JPG, GIF, PNG', null=True, upload_to='adzone/bannerads/', verbose_name='Banner móvil'),
        ),
    ]
