# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerad',
            name='content',
            field=models.ImageField(help_text='Dimensiones: 970×250px</br>Tamaño máximo permitido: 150kb</br>Formato: JPG, GIF, PNG', upload_to='adzone/bannerads/', verbose_name='Banner escritorio'),
        ),
        migrations.AlterField(
            model_name='bannerad',
            name='mobile_content',
            field=models.ImageField(blank=True, help_text='Dimensiones: 300×250px</br>Tamaño máximo permitido: 150kb</br>Formato: JPG, GIF, PNG', null=True, upload_to='adzone/bannerads/', verbose_name='Banner móvil'),
        ),
    ]
