# Generated by Django 4.1.13 on 2024-09-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adzone", "0002_alter_bannerad_content_alter_bannerad_mobile_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adbase",
            name="mobile_url",
            field=models.URLField(
                blank=True,
                help_text="Ídem anterior. Si es la misma dejar en blanco.",
                max_length=500,
                null=True,
                verbose_name="Alternative Advertised URL for mobile.",
            ),
        ),
        migrations.AlterField(
            model_name="adbase",
            name="url",
            field=models.URLField(
                help_text="Siempre debe comenzar con http:// o https:// y si se necesita un timestamp usar %(timestamp)d",
                max_length=500,
                verbose_name="Advertised URL",
            ),
        ),
    ]
