# Generated by Django 4.2.19 on 2025-03-08 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("adzone", "0003_alter_adbase_mobile_url_alter_adbase_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adbase",
            options={"verbose_name": "Ad Base", "verbose_name_plural": "Ads Base"},
        ),
        migrations.AlterField(
            model_name="adbase",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
        migrations.AlterField(
            model_name="adbase",
            name="stop_showing",
            field=models.DateTimeField(
                default=datetime.datetime(9999, 12, 29, 23, 59, 59, 999999),
                verbose_name="Stop showing",
            ),
        ),
        migrations.AlterField(
            model_name="bannerad",
            name="content",
            field=models.ImageField(
                upload_to="adzone/bannerads/", verbose_name="Banner escritorio"
            ),
        ),
        migrations.AlterField(
            model_name="bannerad",
            name="mobile_content",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="adzone/bannerads/",
                verbose_name="Banner móvil",
            ),
        ),
    ]
