# Generated by Django 4.2.19 on 2025-03-08 12:32

import adzone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adzone", "0004_alter_adbase_options_alter_adbase_sites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adbase",
            name="stop_showing",
            field=models.DateTimeField(
                default=adzone.models.get_default_stop_showing,
                verbose_name="Stop showing",
            ),
        ),
    ]
