# Generated by Django 4.2.19 on 2025-03-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adzone", "0005_alter_adbase_stop_showing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bannerad",
            options={"verbose_name": "banner", "verbose_name_plural": "banners"},
        ),
    ]
