# Generated by Django 4.1.4 on 2023-08-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiologue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audiologue', verbose_name='audio'),
        ),
    ]
