# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiologue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audiologue', verbose_name='audio'),
        ),
    ]
