# Generated by Django 4.1.4 on 2024-05-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiologue', '0002_alter_audio_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ('-date_uploaded',)},
        ),
    ]
