# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiologue', '__first__'),
        ('thedaily', '0004_auto_20210615_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amp_click', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiologue.Audio')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thedaily.Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('newsletter_name', models.CharField(max_length=64)),
                ('user_sent', models.PositiveIntegerField(blank=True, null=True)),
                ('subscriber_sent', models.PositiveIntegerField(blank=True, null=True)),
                ('user_refused', models.PositiveIntegerField(blank=True, null=True)),
                ('subscriber_refused', models.PositiveIntegerField(blank=True, null=True)),
                ('user_opened', models.PositiveIntegerField(blank=True, null=True)),
                ('subscriber_opened', models.PositiveIntegerField(blank=True, null=True)),
                ('user_bounces', models.PositiveIntegerField(blank=True, null=True)),
                ('subscriber_bounces', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='newsletterdelivery',
            unique_together=set([('delivery_date', 'newsletter_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='audiostatistics',
            unique_together=set([('subscriber', 'audio')]),
        ),
    ]
