# Generated by Django 4.1.4 on 2023-10-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterdelivery',
            name='subscriber_refused',
        ),
        migrations.RemoveField(
            model_name='newsletterdelivery',
            name='user_refused',
        ),
    ]
