# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='date created')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='date modified')),
                ('status', models.IntegerField(choices=[(1, 'drafted'), (2, 'published'), (3, 'removed')], db_index=True, default=1, help_text='Only %(class)s             with "published" status will be displayed publicly.', verbose_name='status')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('slug', models.SlugField(help_text='Used in         the URL for the Question. Must be unique.', unique=True, verbose_name='slug')),
                ('answer', models.TextField(verbose_name='answer')),
                ('ordering', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='An integer used to order the question             amongst others related to the same topic. If not given this             question will be last in the list.', verbose_name='ordering')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('ordering', 'question', 'slug'),
                'abstract': False,
                'verbose_name_plural': 'questions',
                'verbose_name': 'question',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='date created')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='date modified')),
                ('status', models.IntegerField(choices=[(1, 'drafted'), (2, 'published'), (3, 'removed')], db_index=True, default=1, help_text='Only %(class)s             with "published" status will be displayed publicly.', verbose_name='status')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='Used in         the URL for the topic. Must be unique.', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='A short description of this topic.', verbose_name='description')),
                ('template_name', models.CharField(blank=True, help_text='Optional template to use for this             topic\'s detail page, e.g., "faq/topics/special.html". If not             given the standard template will be used.', max_length=255, verbose_name='template name')),
                ('sites', models.ManyToManyField(related_name='faq_topics', to='sites.Site', verbose_name='sites')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('title', 'slug'),
                'abstract': False,
                'verbose_name_plural': 'topics',
                'verbose_name': 'topic',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='faq.Topic', verbose_name='topic'),
        ),
    ]
