# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='An integer used to order the question amongst others related to the same topic. If not given this             question will be last in the list.', verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(help_text='Used in the URL for the Question. Must be unique.', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(1, 'drafted'), (2, 'published'), (3, 'removed')], db_index=True, default=1, help_text='Only %(class)s with "published" status will be displayed publicly.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(help_text='Used in the URL for the topic. Must be unique.', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.IntegerField(choices=[(1, 'drafted'), (2, 'published'), (3, 'removed')], db_index=True, default=1, help_text='Only %(class)s with "published" status will be displayed publicly.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='template_name',
            field=models.CharField(blank=True, help_text='Optional template to use for this topic\'s detail page, e.g., "faq/topics/special.html". If not             given the standard template will be used.', max_length=255, verbose_name='template name'),
        ),
    ]
