# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videologue', '0001_initial'),
        ('photologue', '0001_initial'),
        ('audiologue', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='full_width_cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo', verbose_name='foto full de portada'),
        ),
        migrations.AddField(
            model_name='printonlyarticle',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_only_articles', to='core.Edition', verbose_name='edici\xf3n'),
        ),
        migrations.AddField(
            model_name='portabledocumentformatpageimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.PortableDocumentFormatPage', verbose_name='p\xe1gina'),
        ),
        migrations.AddField(
            model_name='portabledocumentformatpage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_1', to='core.Article', verbose_name='destacado 1'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_2', to='core.Article', verbose_name='destacado 2'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_3', to='core.Article', verbose_name='destacado 3'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_4', to='core.Article', verbose_name='destacado 4'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_5', to='core.Article', verbose_name='destacado 5'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_6', to='core.Article', verbose_name='destacado 6'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_7', to='core.Article', verbose_name='destacado 7'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_8', to='core.Article', verbose_name='destacado 8'),
        ),
        migrations.AddField(
            model_name='module',
            name='article_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_9', to='core.Article', verbose_name='destacado 9'),
        ),
        migrations.AddField(
            model_name='module',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.Home', verbose_name='portada'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('city', 'country')]),
        ),
        migrations.AddField(
            model_name='journalist',
            name='sections',
            field=models.ManyToManyField(blank=True, to='core.Section', verbose_name='secciones'),
        ),
        migrations.AddField(
            model_name='home',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='core.Category', verbose_name='\xe1rea'),
        ),
        migrations.AddField(
            model_name='home',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_cover_on', to='core.Article', verbose_name='art\xedculo principal'),
        ),
        migrations.AddField(
            model_name='edition',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_edition', to='core.Publication', verbose_name='publicaci\xf3n'),
        ),
        migrations.AddField(
            model_name='category',
            name='full_width_cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo', verbose_name='foto full de portada'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='articles',
            field=models.ManyToManyField(blank=True, to='core.Article', verbose_name='art\xedculos relacionados'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='core.Category', verbose_name='portada de \xe1reas'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='publications',
            field=models.ManyToManyField(blank=True, null=True, to='core.Publication', verbose_name='portada de publicaciones'),
        ),
        migrations.AddField(
            model_name='articleviewedby',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article'),
        ),
        migrations.AddField(
            model_name='articleviewedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleurlhistory',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article'),
        ),
        migrations.AddField(
            model_name='articlerel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article'),
        ),
        migrations.AddField(
            model_name='articlerel',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Edition'),
        ),
        migrations.AddField(
            model_name='articlerel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section'),
        ),
        migrations.AddField(
            model_name='articleextension',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='core.Article', verbose_name='art\xedculo'),
        ),
        migrations.AddField(
            model_name='articlebodyimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_image', to='core.Article', verbose_name='art\xedculo'),
        ),
        migrations.AddField(
            model_name='articlebodyimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='photologue.Photo', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='article',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_core', to='audiologue.Audio', verbose_name='audio'),
        ),
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.ManyToManyField(blank=True, related_name='articles_core', to='core.Journalist', verbose_name='autor/es'),
        ),
        migrations.AddField(
            model_name='article',
            name='continues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continuation', to='core.Article', verbose_name='es continuaci\xf3n de'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_articles_core', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='galer\xeda'),
        ),
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_core', to='core.Location', verbose_name='ubicaci\xf3n'),
        ),
        migrations.AddField(
            model_name='article',
            name='main_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='core.ArticleRel', verbose_name='publicaci\xf3n principal'),
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_core', to='core.Publication', verbose_name='publicaci\xf3n'),
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(null=True, related_name='articles_core', through='core.ArticleRel', to='core.Section', verbose_name='secci\xf3n'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_core', to='videologue.Video', verbose_name='video'),
        ),
        migrations.AddField(
            model_name='article',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='viewed_articles_core', through='core.ArticleViewedBy', to=settings.AUTH_USER_MODEL, verbose_name='visto por'),
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videologue.YouTubeVideo', verbose_name='video de YouTube'),
        ),
        migrations.AlterUniqueTogether(
            name='supplement',
            unique_together=set([('date_published', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='printonlyarticle',
            unique_together=set([('headline', 'edition')]),
        ),
        migrations.AlterUniqueTogether(
            name='portabledocumentformatpage',
            unique_together=set([('content_type', 'object_id', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='articleviewedby',
            unique_together=set([('article', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='articleurlhistory',
            unique_together=set([('article', 'absolute_url')]),
        ),
    ]
