# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-01 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200820_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed10_content',
            field=models.TextField(blank=True, null=True, verbose_name='contenido de incrustado 10'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed10_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='t\xedtulo de incrustado 10'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed11_content',
            field=models.TextField(blank=True, null=True, verbose_name='contenido de incrustado 11'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed11_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='t\xedtulo de incrustado 11'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed12_content',
            field=models.TextField(blank=True, null=True, verbose_name='contenido de incrustado 12'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed12_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='t\xedtulo de incrustado 12'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed13_content',
            field=models.TextField(blank=True, null=True, verbose_name='contenido de incrustado 13'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed13_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='t\xedtulo de incrustado 13'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed14_content',
            field=models.TextField(blank=True, null=True, verbose_name='contenido de incrustado 14'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed14_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='t\xedtulo de incrustado 14'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed9_content',
            field=models.TextField(blank=True, null=True, verbose_name='contenido de incrustado 9'),
        ),
        migrations.AddField(
            model_name='breakingnewsmodule',
            name='embed9_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='t\xedtulo de incrustado 9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(related_name='articles_core', through='core.ArticleRel', to='core.Section', verbose_name='secci\xf3n'),
        ),
        migrations.AlterField(
            model_name='article',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, editable=False, related_name='viewed_articles_core', through='core.ArticleViewedBy', to=settings.AUTH_USER_MODEL, verbose_name='visto por'),
        ),
        migrations.AlterField(
            model_name='breakingnewsmodule',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.Category', verbose_name='portada de \xe1reas'),
        ),
        migrations.AlterField(
            model_name='breakingnewsmodule',
            name='publications',
            field=models.ManyToManyField(blank=True, to='core.Publication', verbose_name='portada de publicaciones'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_1', to='core.Article', verbose_name='destacado 1'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_1_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_2', to='core.Article', verbose_name='destacado 2'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_2_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_3', to='core.Article', verbose_name='destacado 3'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_3_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_4', to='core.Article', verbose_name='destacado 4'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_4_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_5', to='core.Article', verbose_name='destacado 5'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_5_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_6', to='core.Article', verbose_name='destacado 6'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_6_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_7', to='core.Article', verbose_name='destacado 7'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_7_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_8', to='core.Article', verbose_name='destacado 8'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_8_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_9', to='core.Article', verbose_name='destacado 9'),
        ),
        migrations.AlterField(
            model_name='module',
            name='article_9_fixed',
            field=models.BooleanField(verbose_name=b'fijo'),
        ),
        migrations.AlterField(
            model_name='section',
            name='publications',
            field=models.ManyToManyField(blank=True, to='core.Publication', verbose_name='publicaciones'),
        ),
    ]
