# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201001_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='apple_touch_icon_180',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='apple_touch_icon_192',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='apple_touch_icon_512',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='icon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='icon_png',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='icon_png_16',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='icon_png_32',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='open_graph_image',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='subscribe_box_nl_subscribe_anon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='subscribe_box_nl_subscribe_auth',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='subscribe_box_question',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
