# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-28 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201115_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='open_graph_image_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='open_graph_image_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher_logo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher_logo_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher_logo_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
