# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201228_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portabledocumentformatpage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portabledocumentformatpage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='portabledocumentformatpageimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='content',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='content',
        ),
        migrations.DeleteModel(
            name='PortableDocumentFormatPage',
        ),
        migrations.DeleteModel(
            name='PortableDocumentFormatPageImage',
        ),
    ]
