# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210128_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newsletter_periodicity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='newsletter_tagline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribe_box_nl_subscribe_anon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribe_box_nl_subscribe_auth',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribe_box_question',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
