# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210306_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Nombre de usuario de Twitter que se menciona cuando art\xedculos de esta publicaci\xf3n son compartidos en Twitter (escribir sin @)', max_length=15, null=True, verbose_name='Nombre de usuario de Twitter'),
        ),
    ]
