# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-31 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_publication_twitter_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('category',),
                'verbose_name': 'portada de \xe1rea',
                'verbose_name_plural': 'portadas de \xe1rea',
            },
        ),
        migrations.CreateModel(
            name='CategoryHomeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='publicado')),
                ('fixed', models.BooleanField(verbose_name='fijo')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_articles', to='core.Article')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoryHome')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.RemoveField(
            model_name='home',
            name='category',
        ),
        migrations.RemoveField(
            model_name='home',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_1',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_2',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_3',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_4',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_5',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_6',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_7',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_8',
        ),
        migrations.RemoveField(
            model_name='module',
            name='article_9',
        ),
        migrations.RemoveField(
            model_name='module',
            name='home',
        ),
        migrations.AddField(
            model_name='publication',
            name='new_pill',
            field=models.BooleanField(default=False, verbose_name='pill de "nuevo" en el componente de portada'),
        ),
        migrations.AddField(
            model_name='publication',
            name='newsletter_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='newsletter_periodicity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='newsletter_tagline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AddField(
            model_name='categoryhome',
            name='articles',
            field=models.ManyToManyField(through='core.CategoryHomeArticle', to='core.Article'),
        ),
        migrations.AddField(
            model_name='categoryhome',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='core.Category', verbose_name='\xe1rea'),
        ),
    ]
