# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_exclude_from_top_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Habilitar comentarios'),
        ),
        migrations.AlterField(
            model_name='categoryhomearticle',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='fijo'),
        ),
    ]
