# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210722_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='continues',
        ),
        migrations.AlterField(
            model_name='publication',
            name='headline',
            field=models.CharField(max_length=100, verbose_name='t\xedtulo'),
        ),
    ]
