# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211004_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newsletter_automatic_subject',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='newsletter_subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='asunto'),
        ),
    ]
