# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211014_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='newsletter_automatic_subject',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='newsletter_subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='asunto'),
        ),
    ]
