# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211014_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[(b'NE', b'Noticia'), (b'OP', 'Opini\xf3n'), (b'PA', 'Fotograf\xeda'), (b'HT', b'HTML'), (b'CM', b'COMUNIDAD')], db_index=True, max_length=2, null=True, verbose_name='tipo'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type', 'date_published', 'is_published'], name='core_articl_type_442605_idx'),
        ),
    ]
