# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211203_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='t\xedtulo')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='subt\xedtulo')),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Edition', verbose_name='edici\xf3n')),
            ],
            options={
                'verbose_name': 'encabezado de edici\xf3n',
                'verbose_name_plural': 'encabezados de edici\xf3n',
            },
        ),
    ]
