# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-07 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211215_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryhomearticle',
            unique_together=set([('home', 'position')]),
        ),
    ]
