# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220107_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='additional_access',
            field=models.ManyToManyField(blank=True, help_text='Adem\xe1s de los permisos que autom\xe1ticamente se establecen seg\xfan d\xf3nde se publica el art\xedculo, se dar\xe1 el mismo nivel de acceso a los suscriptores de las publicaciones marcadas aqu\xed.', to='core.Publication', verbose_name='extender acceso a suscriptores por publicaci\xf3n'),
        ),
    ]
