# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_article_additional_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField(verbose_name='v\xe1lida hasta')),
            ],
            options={
                'ordering': ('category',),
                'verbose_name': 'newsletter de \xe1rea',
                'verbose_name_plural': 'newsletters de \xe1rea',
            },
        ),
        migrations.CreateModel(
            name='CategoryNewsletterArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='orden')),
                ('featured', models.BooleanField(default=False, verbose_name='incluir s\xf3lo en bloque destacado')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_articles', to='core.Article', verbose_name='art\xedculo')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoryNewsletter')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='categoryhomearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_articles', to='core.Article', verbose_name='art\xedculo'),
        ),
        migrations.AddField(
            model_name='categorynewsletter',
            name='articles',
            field=models.ManyToManyField(through='core.CategoryNewsletterArticle', to='core.Article'),
        ),
        migrations.AddField(
            model_name='categorynewsletter',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to='core.Category', verbose_name='\xe1rea'),
        ),
    ]
