# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-09 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220303_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='articleviews',
            unique_together=set([('article', 'day')]),
        ),
        migrations.AlterIndexTogether(
            name='articleviews',
            index_together=set([('day', 'views')]),
        ),
    ]
