# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220309_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='newsletter_logo',
            field=models.ImageField(blank=True, null=True, upload_to='publications', verbose_name='logo para NL'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications', verbose_name='logo'),
        ),
    ]
