# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220705_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('NE', 'Noticia'), ('OP', 'Opinión'), ('PA', 'Fotografía'), ('HT', 'HTML'), ('CM', 'COMUNIDAD')], db_index=True, max_length=2, null=True, verbose_name='tipo'),
        ),
    ]
