# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-03 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_auto_20220908_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSubscribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('sent', models.DateTimeField(null=True, verbose_name='Fecha de envio')),
                ('tag', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tag')),
                ('overwrite', models.BooleanField(default=False, verbose_name='Sobrescribir notificacion')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article', verbose_name='Articulo')),
            ],
        ),
    ]
