# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_devicesubscribed_pushnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesubscribed',
            name='subscription_info',
            field=models.CharField(max_length=1024),
        ),
    ]
