# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20221015_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='new_pill',
            field=models.BooleanField(default=False, verbose_name='pill de "nuevo" en el componente de portada y menú'),
        ),
    ]
