# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-25 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20221015_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ipfs_cid',
            field=models.TextField(blank=True, help_text='CID de la nota en IPFS', null=True, verbose_name='id de IPFS'),
        ),
        migrations.AddField(
            model_name='article',
            name='ipfs_upload',
            field=models.BooleanField(default=True, verbose_name='Publicar en IPFS'),
        ),
    ]
