# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20221025_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='solana_signature',
            field=models.TextField(blank=True, help_text='Firma del autor desde su wallet en Solana', null=True, verbose_name='Firma de Solana'),
        ),
    ]
