# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20221017_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dropdown_menu',
            field=models.BooleanField(default=False, verbose_name='Usar menú desplegable en menú superior de escritorio con las secciones del área'),
        ),
    ]
