# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_category_dropdown_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ipfs_cid',
            field=models.TextField(blank=True, help_text='CID del artículo en IPFS', null=True, verbose_name='id de IPFS'),
        ),
        migrations.AddField(
            model_name='article',
            name='ipfs_upload',
            field=models.BooleanField(default=False, verbose_name='Publicar en IPFS'),
        ),
    ]
