# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20221204_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='solana_signature',
            field=models.TextField(blank=True, help_text='Firma del autor en Solana', null=True, verbose_name='Firma de Solana'),
        ),
        migrations.AddField(
            model_name='article',
            name='solana_signature_address',
            field=models.TextField(blank=True, help_text='Wallet autora de la firma en Solana', null=True, verbose_name='Wallet de Solana'),
        ),
    ]
