# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20221229_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
