# Generated by Django 4.1.4 on 2023-08-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_article_sp_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articlecollection',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='articlecollectionrelated',
            name='article',
            field=models.ForeignKey(limit_choices_to={'articlecollection__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='artículo'),
        ),
    ]
