# Generated by Django 4.1.4 on 2024-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_category_newsletter_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newsletter_extra_context',
            field=models.JSONField(default=dict, help_text='Diccionario Python en formato JSON que se utilizará como contexto al inicio de la construcción del contexto predeterminado, sus entradas, si hay colisión, serían sobreescritas por el comando de envío.<br>Ejemplo: <code>{"custom_footer_msg": "Esta newsletter fue generada utilizando utopia-cms"}</code>', verbose_name='Contexto extra para newsletter'),
        ),
    ]
