# Generated by Django 4.1.4 on 2024-07-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_journalist_ig"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edition",
            unique_together={("date_published", "publication")},
        ),
    ]
