# Generated by Django 4.1.4 on 2024-07-25 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_edition_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="publicado"
            ),
        ),
        migrations.AlterField(
            model_name="edition",
            name="date_published",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="fecha de publicación",
            ),
        ),
        migrations.AlterField(
            model_name="supplement",
            name="date_published",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="fecha de publicación",
            ),
        ),
    ]
