# Generated by Django 4.1.4 on 2024-07-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_article_full_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alt_desc_metadata',
            field=models.TextField(blank=True, help_text='Aplica a metadatos: meta description, Open Graph y Schema en el <head> de la página del artículo.<br>Si se deja vacío aplica Descripción principal.', null=True, verbose_name='descripción alternativa para metadatos'),
        ),
        migrations.AddField(
            model_name='article',
            name='alt_desc_newsletters',
            field=models.TextField(blank=True, help_text='Aplica en todos los newsletters que aparezca el artículo.<br>Si se deja vacío aplica Descripción principal', null=True, verbose_name='descripción alternativa para newsletters'),
        ),
        migrations.AddField(
            model_name='article',
            name='alt_title_metadata',
            field=models.CharField(blank=True, help_text='Aplica a metadatos: meta title, Open Graph y Schema en el <head> de la página del artículo.<br>Si se deja vacío aplica Título principal.', max_length=200, null=True, verbose_name='título alternativo para metadatos'),
        ),
        migrations.AddField(
            model_name='article',
            name='alt_title_newsletters',
            field=models.CharField(blank=True, help_text='Aplica en todos los newsletters que aparezca el artículo.<br>Si se deja vacío aplica Título principal.', max_length=200, null=True, verbose_name='título alternativo para newsletters'),
        ),
    ]
