# Generated by Django 4.1.4 on 2024-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_article_alt_desc_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="alt_desc_metadata",
            field=models.TextField(
                blank=True,
                help_text="Aplica a metadatos: meta description, Open Graph y Schema en el &lt;head&gt; de la página del artículo.<br>Si se deja vacío aplica Descripción principal.",
                null=True,
                verbose_name="descripción alternativa para metadatos",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="alt_desc_newsletters",
            field=models.TextField(
                blank=True,
                help_text="Aplica en newsletters donde aparezca el artículo.<br>Si se deja vacío aplica Descripción principal",
                null=True,
                verbose_name="descripción alternativa para newsletters",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="alt_title_metadata",
            field=models.CharField(
                blank=True,
                help_text="Aplica a metadatos: meta title, Open Graph y Schema en el &lt;head&gt; de la página del artículo.<br>Si se deja vacío aplica Título principal.",
                max_length=200,
                null=True,
                verbose_name="título alternativo para metadatos",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="alt_title_newsletters",
            field=models.CharField(
                blank=True,
                help_text="Aplica en newsletters donde aparezca el artículo.<br>Si se deja vacío aplica Título principal.",
                max_length=200,
                null=True,
                verbose_name="título alternativo para newsletters",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="deck",
            field=models.TextField(
                blank=True,
                help_text="Se muestra en la página del artículo debajo del título.",
                null=True,
                verbose_name="descripción",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="home_top_deck",
            field=models.TextField(
                blank=True,
                help_text="Se muestra en los destacados de la portada, en el caso de estar vacío se muestra la bajada del artículo.",
                null=True,
                verbose_name="bajada en destacados",
            ),
        ),
    ]
