# Generated by Django 4.1.4 on 2024-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_article_alt_desc_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="included_in_category_menu",
            field=models.BooleanField(
                default=True, verbose_name="incluída en el menú del área"
            ),
        ),
    ]
