# Generated by Django 4.1.4 on 2024-08-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_publication_extra_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='lnkin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='mtdn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mastodon'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='thds',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='threads'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='tktk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tiktok'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='ytb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube'),
        ),
    ]
