# Generated by Django 4.1.4 on 2024-08-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_journalist_lnkin_journalist_mtdn_journalist_thds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalist",
            name="gp",
        ),
        migrations.AddField(
            model_name="journalist",
            name="bs",
            field=models.URLField(blank=True, null=True, verbose_name="bluesky"),
        ),
        migrations.AddField(
            model_name="journalist",
            name="other_one",
            field=models.URLField(blank=True, null=True, verbose_name="otro 1"),
        ),
        migrations.AddField(
            model_name="journalist",
            name="other_three",
            field=models.URLField(blank=True, null=True, verbose_name="otro 3"),
        ),
        migrations.AddField(
            model_name="journalist",
            name="other_two",
            field=models.URLField(blank=True, null=True, verbose_name="otro 2"),
        ),
        migrations.AddField(
            model_name="journalist",
            name="tr",
            field=models.URLField(blank=True, null=True, verbose_name="tumblr"),
        ),
        migrations.AddField(
            model_name="journalist",
            name="tw",
            field=models.URLField(blank=True, null=True, verbose_name="twitch"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="fb",
            field=models.URLField(blank=True, null=True, verbose_name="facebook"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="ig",
            field=models.URLField(blank=True, null=True, verbose_name="instagram"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="lnkin",
            field=models.URLField(blank=True, null=True, verbose_name="linkedin"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="mtdn",
            field=models.URLField(blank=True, null=True, verbose_name="mastodon"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="thds",
            field=models.URLField(blank=True, null=True, verbose_name="threads"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="tktk",
            field=models.URLField(blank=True, null=True, verbose_name="tiktok"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="tt",
            field=models.URLField(blank=True, null=True, verbose_name="X"),
        ),
        migrations.AlterField(
            model_name="journalist",
            name="ytb",
            field=models.URLField(blank=True, null=True, verbose_name="youtube"),
        ),
    ]
