# Generated by Django 4.1.13 on 2024-11-01 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videologue", "0002_alter_video_byline_alter_video_caption_and_more"),
        ("audiologue", "0003_alter_audio_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photologue", "0013_alter_watermark_image"),
        ("core", "0047_remove_journalist_gp_journalist_bs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="audio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_%(app_label)s",
                to="audiologue.audio",
                verbose_name="audio",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_articles_%(app_label)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="photologue.gallery",
                verbose_name="galería",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_%(app_label)s",
                to="core.location",
                verbose_name="ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="photologue.photo",
                verbose_name="imagen",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_%(app_label)s",
                to="core.publication",
                verbose_name="publicación",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_%(app_label)s",
                to="videologue.video",
                verbose_name="video",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="youtube_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videologue.youtubevideo",
                verbose_name="video de YouTube",
            ),
        ),
    ]
