# Generated by Django 4.1.13 on 2024-12-10 10:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_article_to_be_published"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="breakingnewsmodule",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
    ]
