# Generated by Django 4.1.13 on 2024-12-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_breakingnewsmodule_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articlerel",
            unique_together=set(),
        ),
    ]
