# Generated by Django 4.2.19 on 2025-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_perplexityapisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ia_used',
            field=models.BooleanField(default=False, editable=False, help_text='Indica si se utilizó IA en este artículo.'),
        ),
    ]
