# Generated by Django 4.1.13 on 2024-12-16 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_articlerel_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultNewsletter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        default=django.utils.timezone.now,
                        unique=True,
                        verbose_name="fecha",
                    ),
                ),
            ],
            options={
                "verbose_name": "newsletter default",
                "verbose_name_plural": "newsletters default",
                "ordering": ("-day",),
                "get_latest_by": "day",
            },
        ),
        migrations.CreateModel(
            name="DefaultNewsletterArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="orden"
                    ),
                ),
                (
                    "include_photo",
                    models.BooleanField(default=False, verbose_name="incluir foto"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        limit_choices_to={"is_published": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_newsletter_articles",
                        to="core.article",
                        verbose_name="artículo",
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.defaultnewsletter",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="defaultnewsletter",
            name="articles",
            field=models.ManyToManyField(
                related_name="default_newsletters_m2m",
                through="core.DefaultNewsletterArticle",
                to="core.article",
            ),
        ),
    ]
