# Generated by Django 4.2.19 on 2025-06-06 22:17

from django.db import migrations

def create_use_ia_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='use_ia')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_article_ia_used_field'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_use_ia_group),
    ]
