# Generated by Django 4.1.13 on 2025-01-02 13:32

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_article_alt_desc_metadata_alter_article_deck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="version",
            field=concurrency.fields.IntegerVersionField(
                default=0, help_text="record revision number"
            ),
        ),
    ]
