# Generated by Django 4.2.19 on 2025-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_create_use_ia_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='copy_para_redes',
            field=models.CharField(blank=True, help_text='Texto que sera utilizado en redes sociales.', max_length=200),
        ),
        migrations.AddField(
            model_name='perplexityapisettings',
            name='activar_asistente',
            field=models.BooleanField(default=True, help_text='para activar o desactivar el uso del asistente IA '),
        ),
        migrations.AddField(
            model_name='perplexityapisettings',
            name='conocimiento',
            field=models.TextField(blank=True, help_text='Enlaces a los articulos ejemplos.'),
        ),
    ]
