# Generated by Django 4.2.19 on 2025-06-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_article_copy_para_redes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perplexityapisettings',
            name='nombre_del_asistente',
            field=models.CharField(default='tIA', help_text='Nombre del asistente IA a utilizar', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='copy_para_redes',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
