# Generated by Django 4.1.13 on 2025-01-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_article_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="newsletter_header_color",
            field=models.CharField(
                default="#262626", max_length=7, verbose_name="color de cabezal para NL"
            ),
        ),
    ]
