# Generated by Django 4.2.19 on 2025-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_perplexityapisettings_nombre_del_asistente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perplexityapisettings',
            name='conocimiento',
        ),
    ]
