# Generated by Django 4.1.13 on 2025-01-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_category_newsletter_header_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlerel",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.article",
                verbose_name="artículo",
            ),
        ),
        migrations.AlterField(
            model_name="articlerel",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.edition",
                verbose_name="edición",
            ),
        ),
        migrations.AlterField(
            model_name="articlerel",
            name="home_top",
            field=models.BooleanField(
                default=False,
                help_text="Si está marcado, el artículo aparecerá en los destacados de la edición correspondiente.",
                verbose_name="destacado en portada",
            ),
        ),
        migrations.AlterField(
            model_name="articlerel",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.section",
                verbose_name="sección",
            ),
        ),
        migrations.AlterField(
            model_name="articlerel",
            name="top_position",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="orden en destacados de portada"
            ),
        ),
    ]
