# Generated by Django 4.2.19 on 2025-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_perplexityapisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='copy_para_redes',
            field=models.TextField(blank=True),
        ),
    ]
