# Generated by Django 4.2.19 on 2025-03-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_articlerel_article_alter_articlerel_edition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="newsletter_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
