# Generated by Django 4.2.19 on 2025-06-17 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_alter_article_copy_para_redes"),
    ]

    operations = [
        migrations.AddField(
            model_name="perplexityapisettings",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="La cantidad de aleatoriedad en la respuesta, valorada entre 0 y 2. Los valores bajos (por ejemplo, 0.1) hacen que la salida sea más enfocada, determinista y menos creativa. Los valores altos (por ejemplo, 1.5) hacen que la salida sea más aleatoria y creativa. Usa valores bajos para tareas de recuperación de información o hechos y valores altos para aplicaciones creativas. Por defecto se usa 0.2",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)],
            ),
        ),
    ]
