# Generated by Django 4.2.19 on 2025-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_category_newsletter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleextension',
            options={'ordering': ['position'], 'verbose_name': 'recuadro', 'verbose_name_plural': 'recuadros'},
        ),
        migrations.AddField(
            model_name='articleextension',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
