# Generated by Django 4.2.19 on 2025-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_alter_articleextension_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleextension",
            options={
                "ordering": ["order"],
                "verbose_name": "recuadro",
                "verbose_name_plural": "recuadros",
            },
        ),
        migrations.RemoveField(
            model_name="articleextension",
            name="position",
        ),
        migrations.AddField(
            model_name="articleextension",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="orden"
            ),
        ),
    ]
