# Generated by Django 4.2.29 on 2026-03-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_perplexityapisettings_result_instructions"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="articleviews",
            index_together=set(),
        ),
        migrations.AlterField(
            model_name="articleviews",
            name="day",
            field=models.DateField(),
        ),
        migrations.AlterIndexTogether(
            name="articleviews",
            index_together={("day", "article", "views")},
        ),
    ]
