# Generated by Django 4.2.19 on 2025-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photologue", "0013_alter_watermark_image"),
        ("core", "0060_alter_articleextension_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlebodyimage",
            options={
                "ordering": ["order"],
                "verbose_name": "imagen",
                "verbose_name_plural": "imágenes",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="body_images",
            field=models.ManyToManyField(
                related_name="related_articles_%(app_label)s",
                through="core.ArticleBodyImage",
                to="photologue.photo",
            ),
        ),
        migrations.AddField(
            model_name="articlebodyimage",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="orden"
            ),
        ),
        migrations.AlterField(
            model_name="articleextension",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recuadros",
                to="core.article",
                verbose_name="artículo",
            ),
        ),
        migrations.AlterField(
            model_name="articleextension",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="orden"
            ),
        ),
    ]
