# Generated by Django 4.2.29 on 2026-03-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_articleviews_index_together_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_published", "slug"], name="core_articl_is_publ_cf075e_idx"
            ),
        ),
    ]
