# Generated by Django 4.2.19 on 2026-03-13 19:18

from django.db import migrations


def add_google_extended_rule(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Rule = apps.get_model("robots", "Rule")
    Url = apps.get_model("robots", "Url")

    site = Site.objects.order_by("id").first()
    url_all, _ = Url.objects.get_or_create(pattern="/")
    rule, _ = Rule.objects.get_or_create(robot="Google-Extended")
    rule.sites.add(site)
    rule.allowed.add(url_all)


def remove_google_extended_rule(apps, schema_editor):
    Rule = apps.get_model("robots", "Rule")
    Rule.objects.filter(robot="Google-Extended").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_perplexityapisettings_result_instructions"),
        ("robots", "__first__"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(add_google_extended_rule, remove_google_extended_rule),
    ]
