# Generated by Django 4.2.19 on 2025-03-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videologue', '0003_alter_video_date_uploaded'),
        ('core', '0061_alter_articlebodyimage_options_article_body_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='youtube_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videologue.youtubevideo', verbose_name='Video de YouTube en la portada de área'),
        ),
        migrations.AddField(
            model_name='publication',
            name='youtube_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videologue.youtubevideo', verbose_name='Video de YouTube en la portada'),
        ),
    ]
