# Generated by Django 4.2.19 on 2025-04-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_category_youtube_video_publication_youtube_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalist",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="nombre"),
        ),
    ]
