# Generated by Django 4.2.19 on 2025-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_alter_journalist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalist",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="slug"),
        ),
    ]
