# Generated by Django 4.2.19 on 2025-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_journalist_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalist",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=128,
                null=True,
                upload_to="journalist",
                verbose_name="imagen",
            ),
        ),
    ]
