# Generated by Django 4.2.19 on 2025-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_alter_journalist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="header_display",
            field=models.CharField(
                choices=[("FW", "Ancho completo"), ("BG", "Grande")],
                default="BG",
                max_length=2,
                verbose_name="estilo de cabezal",
            ),
        ),
    ]
