# Generated by Django 4.2.21 on 2025-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_alter_article_header_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlebodyimage",
            name="display",
            field=models.CharField(
                choices=[
                    ("BG", "Ancho regular"),
                    ("MD", "Ancho amplio"),
                    ("FW", "Ancho completo"),
                ],
                default="BG",
                max_length=2,
                verbose_name="display",
            ),
        ),
    ]
