# Generated by Django 4.2.23 on 2025-08-21 10:41

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_alter_articlebodyimage_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerplexityAPISettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_del_asistente",
                    models.CharField(
                        default="tIA",
                        help_text="Nombre del asistente IA a utilizar",
                        max_length=50,
                    ),
                ),
                (
                    "activar_asistente",
                    models.BooleanField(
                        default=True,
                        help_text="para activar o desactivar el uso del asistente IA ",
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        default="https://api.perplexity.ai/chat/completions",
                        help_text="Endpoint de la API de Perplexity",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("sonar-pro", "sonar-pro"),
                            ("sonar", "sonar"),
                            ("sonar-reasoning-pro", "sonar-reasoning-pro"),
                            ("sonar-reasoning", "sonar-reasoning"),
                            ("sonar-deep-research", "sonar-deep-research"),
                            ("r1-1776", "r1-1776"),
                        ],
                        default="sonar",
                        help_text="Modelo de IA a utilizar",
                        max_length=50,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        help_text="La cantidad de aleatoriedad en la respuesta, valorada entre 0 y 2. Los valores bajos (por ejemplo, 0.1) hacen que la salida sea más enfocada, determinista y menos creativa. Los valores altos (por ejemplo, 1.5) hacen que la salida sea más aleatoria y creativa. Usa valores bajos para tareas de recuperación de información o hechos y valores altos para aplicaciones creativas. Por defecto se usa 0.2",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "context_size",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        default="low",
                        help_text='Opcion "search_context_size" a utilizar: low, medium o high',
                        max_length=10,
                    ),
                ),
                (
                    "search_domain_filter",
                    models.CharField(
                        blank=True,
                        default="ladiaria.com.uy",
                        help_text='Dominios permitidos o restringidos, separados por coma, si queires excliur alguno use "-" delante del dominio, ej. -redis.com',
                        max_length=500,
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Máximo de tokens por respuesta, si no se configura se usa el valor por defecto que depende del modelo escogido.",
                        null=True,
                    ),
                ),
                (
                    "default_context",
                    models.TextField(
                        default="Responde en español de manera clara y concisa.",
                        help_text="Contexto por defecto que siempre se enviará a Perplexity",
                        validators=[core.models.validar_default_context],
                    ),
                ),
                (
                    "result_instructions",
                    models.TextField(
                        default='\nPor favor, devuelve un objeto JSON que contenga los siguientes campos: metatitles, copys.\n- El campo "metatitles" debe ser un array de exactamente 3 strings, cada uno con un metatítulo diferente y adecuado para Google Discover, siguiendo el estilo de la diaria.\n- El campo "copys" debe ser un array de exactamente 2 strings. Cada string debe incluir primero el copy para redes sociales y, en la misma string y separado por un salto de línea, los hashtags correspondientes.\n- No agregues elementos adicionales ni comentarios fuera del objeto JSON.\n\nEjemplo de formato esperado:\n{\n  "metatitles": [\n    "Metatítulo 1",\n    "Metatítulo 2",\n    "Metatítulo 3"\n  ],\n  "copys": [\n    "Copy para redes sociales 1.\\n#Hashtag1 #Hashtag2",\n    "Copy para redes sociales 2.\\n#Hashtag3 #Hashtag4"\n  ]\n}',
                        help_text="Describe detalladamente cómo debe presentarse el resultado. Ejemplo: 'Incluya unidades y redondee a dos decimales.'",
                        validators=[core.models.validar_ejemplo_formato],
                        verbose_name="Instrucciones para el resultado",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="copy_para_redes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="ia_used",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Indica si se utilizó IA en este artículo.",
            ),
        ),
    ]
