# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 04:12

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import photologue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('info', models.EmailField(blank=True, help_text='Ingrese aqu\xed informaci\xf3n extra, como mail de contacto o lo que considere pertinente.', max_length=254, null=True, verbose_name='informaci\xf3n')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaci\xf3n')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'date_created',
                'verbose_name': 'agencia',
                'verbose_name_plural': 'agencias',
            },
        ),
        migrations.CreateModel(
            name='PhotoExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focuspoint_x', models.CharField(default=0, max_length=10, verbose_name='punto de foco horizontal (x)')),
                ('focuspoint_y', models.CharField(default=0, max_length=10, verbose_name='punto de foco vertical (y)')),
                ('radius_length', models.SmallIntegerField(blank=True, help_text='mitad del lado del cuadrado para recorte (pixeles)', null=True, verbose_name='radio')),
                ('square_version', models.ImageField(blank=True, null=True, upload_to=photologue.models.get_storage_path, verbose_name='versi\xf3n cuadrada')),
                ('weight', models.SmallIntegerField(default=0, help_text='el n\xfamero m\xe1s bajo se muestra primero.', verbose_name='orden de la imagen en la galer\xeda')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photologue_ladiaria.Agency', verbose_name='agencia')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='photologue.Photo')),
            ],
            options={
                'verbose_name': 'configuraci\xf3n extra',
                'verbose_name_plural': 'configuraciones extra',
            },
            bases=(models.Model, core.utils.CT),
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electr\xf3nico')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaci\xf3n')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'date_created',
                'verbose_name': 'fot\xf3grafo',
                'verbose_name_plural': 'fot\xf3grafos',
            },
        ),
        migrations.AddField(
            model_name='photoextended',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photologue_ladiaria.Photographer', verbose_name='autor'),
        ),
    ]
