# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_ladiaria', '0002_photoextended_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='info',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='photoextended',
            name='type',
            field=models.CharField(choices=[('f', 'Foto'), ('i', 'Ilustración')], default='f', max_length=1, verbose_name='tipo'),
        ),
    ]
