# Generated by Django 4.1.4 on 2023-10-03 11:13

from django.db import migrations, models
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_ladiaria', '0003_alter_agency_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoextended',
            name='square_version',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=photologue.models.get_storage_path, verbose_name='versión cuadrada'),
        ),
    ]
