# Generated by Django 4.1.4 on 2024-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_ladiaria', '0004_alter_photoextended_square_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoextended',
            name='enable_webp',
            field=models.BooleanField(default=True, verbose_name='Convertir a webp'),
        ),
    ]
