# Generated by Django 4.1.4 on 2024-10-31 18:34

from django.db import migrations, models
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_ladiaria', '0004_alter_photoextended_square_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoextended',
            name='original_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=photologue.models.get_storage_path, verbose_name='imagen original'),
        ),
    ]
