# Generated by Django 4.2.19 on 2025-03-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photologue_ladiaria", "0004_alter_photoextended_square_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoextended",
            name="alt_text",
            field=models.TextField(
                blank=True,
                help_text="Descripción de la imagen para quienes no puedan verla. Mejora accesibilidad y SEO. Si se deja vacío se utilizará la leyenda.<br>Longitud recomendada:<br>Ideal: menos de 125 caracteres.<br>Máxima: menos de 250 caracteres<br>Exceptional: más de 250 caracteres para describir un gráfico por ejemplo.",
                null=True,
                verbose_name="texto alternativo (alt text)",
            ),
        ),
    ]
