# Generated by Django 4.2.19 on 2025-05-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photologue_ladiaria", "0005_photoextended_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="photographer",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="nombre"),
        ),
    ]
