# Generated by Django 4.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_ladiaria', '0005_photoextended_original_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoextended',
            name='original_image',
        ),
    ]
