# Generated by Django 4.1.4

from django.db import migrations, models
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_ladiaria', '0006_remove_photoextended_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoextended',
            name='last_original_uploaded',
            field=models.ImageField(
                blank=True,
                help_text='Copia del archivo tal como se subió la última vez (solo lectura).',
                max_length=255,
                null=True,
                upload_to=photologue.models.get_storage_path,
                verbose_name='última subida original',
            ),
        ),
    ]
