# Generated by Django 4.2.19 on 2026-02-17 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeLayout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "scheduled_time",
                    models.TimeField(
                        help_text="Time from which this layout becomes active"
                    ),
                ),
                (
                    "is_manual_override",
                    models.BooleanField(
                        default=False,
                        help_text="When active, this layout takes priority over scheduled ones",
                    ),
                ),
                (
                    "grid_data",
                    models.JSONField(
                        default=list, help_text="GridStack serialized layout"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "manual_override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homev4_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.publication",
                        verbose_name="publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "home layout",
                "verbose_name_plural": "home layouts",
                "ordering": ["-scheduled_time"],
            },
        ),
    ]
