# Generated by Django 4.2.19 on 2026-02-17 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0061_alter_article_type_alter_supplement_name"),
        ("homev4", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homelayout",
            options={
                "ordering": ["-scheduled_time"],
                "verbose_name": "layout de portada",
                "verbose_name_plural": "layouts de portada",
            },
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="grid_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Layout serializado de GridStack",
                verbose_name="datos del layout",
            ),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="is_manual_override",
            field=models.BooleanField(
                default=False,
                help_text="Cuando está activo, este layout tiene prioridad sobre los programados",
                verbose_name="override manual",
            ),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="manual_override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homev4_overrides",
                to=settings.AUTH_USER_MODEL,
                verbose_name="activado por",
            ),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado"),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
                verbose_name="publicación",
            ),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="scheduled_time",
            field=models.TimeField(
                help_text="Hora desde la que este layout está activo",
                verbose_name="hora programada",
            ),
        ),
    ]
