# Generated by Django 4.2.19 on 2026-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homev4", "0004_homelayout_day_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="homelayout",
            name="ends_next_day",
            field=models.BooleanField(
                default=False,
                help_text="Activar cuando el rango horario cruza la medianoche (ej: 15:00 del sábado → 06:00 del domingo)",
                verbose_name="termina al día siguiente",
            ),
        ),
        migrations.AlterField(
            model_name="homelayout",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lv", "Lunes a Viernes"),
                    ("lmjv", "Lunes, Miércoles, Jueves y Viernes"),
                    ("sa", "Sábado"),
                    ("do", "Domingo"),
                    ("lu", "Lunes"),
                    ("ma", "Martes"),
                    ("mi", "Miércoles"),
                    ("ju", "Jueves"),
                    ("vi", "Viernes"),
                ],
                max_length=4,
                null=True,
                verbose_name="día",
            ),
        ),
    ]
