# Generated by Django 4.2.19 on 2026-03-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homev4", "0005_add_lmjv_day_and_ends_next_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homelayout",
            options={
                "ordering": ["day", "start_time"],
                "verbose_name": "programación de portada",
                "verbose_name_plural": "programaciones de portada",
            },
        ),
    ]
