# Generated by Django 4.2.19 on 2026-04-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homev4", "0007_create_layout_editors_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="homelayout",
            name="pending_grid_data",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Staging area escrito por el editor Preview 5am. La tarea programada lo mueve a grid_data a las 5am.",
                null=True,
                verbose_name="layout pendiente 5am",
            ),
        ),
    ]
