# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epubparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epubfile',
            name='f',
            field=models.FileField(upload_to='epubparser/%Y/%m/%d'),
        ),
    ]
