# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-22 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100, verbose_name=b't\xc3\xadtulo')),
                ('body', models.TextField(verbose_name=b'cuerpo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'fecha de creaci\xc3\xb3n')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name=b'usuario')),
            ],
            options={
                'verbose_name': 'contribuci\xf3n',
                'verbose_name_plural': 'contribuciones',
            },
        ),
    ]
