# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberarticle',
            name='type',
            field=models.CharField(blank=True, choices=[('NE', 'Noticia'), ('OP', 'Opinión'), ('PA', 'Fotografía'), ('HT', 'HTML'), ('CM', 'COMUNIDAD')], db_index=True, max_length=2, null=True, verbose_name='tipo'),
        ),
        migrations.AddIndex(
            model_name='subscriberarticle',
            index=models.Index(fields=['type', 'date_published', 'is_published'], name='comunidad_s_type_ca7570_idx'),
        ),
    ]
