# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberarticle',
            name='type',
            field=models.CharField(blank=True, choices=[(b'NE', b'Noticia'), (b'OP', 'Opini\xf3n'), (b'PA', 'Fotograf\xeda'), (b'HT', b'HTML'), (b'CM', b'COMUNIDAD')], db_index=True, max_length=2, null=True, verbose_name='tipo'),
        ),
        migrations.AddIndex(
            model_name='subscriberarticle',
            index=models.Index(fields=[b'type', b'date_published', b'is_published'], name='comunidad_s_type_ca7570_idx'),
        ),
    ]
