# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_auto_20211203_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='cupo general'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='quota',
            field=models.PositiveIntegerField(default=1, verbose_name='cupo por suscriptor'),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='comment',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.Beneficio', verbose_name='beneficio'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='used',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utilizado'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='header_display',
            field=models.CharField(blank=True, choices=[('FW', 'Ancho completo'), ('BG', 'Grande')], default='BG', max_length=2, null=True, verbose_name='tipo de cabezal'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='home_display',
            field=models.CharField(blank=True, choices=[('I', 'Imagen'), ('A', 'Audio'), ('V', 'Video')], max_length=2, null=True, verbose_name='mostrar en portada'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='home_header_display',
            field=models.CharField(blank=True, choices=[('FW', 'Ancho completo'), ('FF', 'Medio y medio'), ('SM', 'Chico')], default='SM', max_length=2, null=True, verbose_name='tipo de cabezal cuando es portada'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='type',
            field=models.CharField(blank=True, choices=[('NE', 'Noticia'), ('OP', 'Opinión'), ('PA', 'Fotografía'), ('HT', 'HTML'), ('CM', 'COMUNIDAD')], db_index=True, max_length=2, null=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='topuser',
            name='type',
            field=models.CharField(choices=[('WEEK', 'WEEK'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], max_length=20),
        ),
    ]
