# Generated by Django 4.1.4 on 2023-08-28 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('videologue', '0002_alter_video_byline_alter_video_caption_and_more'),
        ('core', '0033_article_sp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audiologue', '0002_alter_audio_file'),
        ('comunidad', '0003_auto_20211203_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberarticle',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_%(app_label)s', to='audiologue.audio', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='body',
            field=martor.models.MartorField(verbose_name='cuerpo'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='byline',
            field=models.ManyToManyField(blank=True, related_name='articles_%(app_label)s', to='core.journalist', verbose_name='autor/es'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_articles_%(app_label)s', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_%(app_label)s', to='core.location', verbose_name='ubicación'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_%(app_label)s', to='core.publication', verbose_name='publicación'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_%(app_label)s', to='videologue.video', verbose_name='video'),
        ),
    ]
