# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_subscriberarticle_solana_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberarticle',
            name='solana_signature_address',
            field=models.TextField(blank=True, help_text='Wallet autora de la firma en Solana', null=True, verbose_name='Wallet de Solana'),
        ),
        migrations.AlterField(
            model_name='subscriberarticle',
            name='solana_signature',
            field=models.TextField(blank=True, help_text='Firma del autor en Solana', null=True, verbose_name='Firma de Solana'),
        ),
    ]
