# Generated by Django 4.1.4 on 2024-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comunidad", "0007_alter_subscriberarticle_deck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuito",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="descripcion"),
        ),
        migrations.AddField(
            model_name="circuito",
            name="general_quota",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="cupo general"
            ),
        ),
        migrations.AddField(
            model_name="circuito",
            name="quota_type",
            field=models.CharField(
                choices=[("C", "Por circuito"), ("B", "Por beneficio")],
                default="B",
                max_length=1,
            ),
        ),
    ]
