# Generated by Django 4.1.4 on 2024-09-17 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("comunidad", "0008_circuito_description_circuito_general_quota_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro",
            name="issued",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="circuito",
            name="general_quota",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="cupo general por suscriptor"
            ),
        ),
        migrations.AlterField(
            model_name="registro",
            name="used",
            field=models.DateTimeField(blank=True, null=True, verbose_name="utilizado"),
        ),
    ]
