# Generated by Django 4.1.4 on 2024-09-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_remove_circuito_quota_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
