# Generated by Django 4.1.4 on 2024-10-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0011_beneficio_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'permissions': [('verify_registro', 'Can verify registro')]},
        ),
    ]
