# Generated by Django 4.1.4 on 2024-10-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thedaily', '0013_alter_subscriber_city_alter_subscriber_country'),
        ('comunidad', '0012_alter_registro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thedaily.subscriber', verbose_name='suscriptor'),
        ),
    ]
