# Generated by Django 4.2.29 on 2026-03-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidad", "0015_subscriberarticle_to_be_published"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscriberarticle",
            index=models.Index(
                fields=["is_published", "slug"], name="comunidad_s_is_publ_fca924_idx"
            ),
        ),
    ]
