# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidad", "0016_subscriberarticle_comunidad_s_is_publ_fca924_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="nombre"),
        ),
        migrations.AddField(
            model_name="registro",
            name="phone",
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name="celular"),
        ),
        migrations.AddField(
            model_name="registro",
            name="dependents",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="menores a cargo"),
        ),
        migrations.AddField(
            model_name="registro",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notas"),
        ),
        migrations.AlterModelOptions(
            name="registro",
            options={
                "permissions": [
                    ("verify_registro", "Can verify registro"),
                    ("export_registro", "Can export registro data"),
                ],
            },
        ),
    ]
