# Generated by Django 4.2.19 on 2025-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidad", "0016_alter_subscriberarticle_deck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriberarticle",
            name="header_display",
            field=models.CharField(
                choices=[("FW", "Ancho completo"), ("BG", "Grande")],
                default="BG",
                max_length=2,
                verbose_name="estilo de cabezal",
            ),
        ),
    ]
