# Generated by Django 4.2.29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comunidad", "0017_registro_name_phone_dependents_notes_export_perm"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficio",
            name="max_uses",
            field=models.PositiveIntegerField(default=1, verbose_name="usos máximos"),
        ),
        migrations.CreateModel(
            name="RegistroUse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de uso"
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uses",
                        to="comunidad.registro",
                        verbose_name="registro",
                    ),
                ),
            ],
            options={
                "verbose_name": "uso de registro",
                "verbose_name_plural": "usos de registro",
                "ordering": ["used_at"],
            },
        ),
    ]
