# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidad", "0018_beneficio_max_uses_registrouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficio",
            name="whatsapp_template_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="plantilla de WhatsApp",
            ),
        ),
    ]
