import logging

from django.conf import settings
from django.utils.timezone import localtime

from . import SendNLCommand


LOG_SUFFIX = 'send_command_testlog'


class Command(SendNLCommand):
    help = 'Manually test the output and log file entries generated by calls to log methods in SendNLCommand'
    """
    Expected behavior:
    - when this runs under cron with DEBUG=False and the default verbosity level, the output (if any) will trigger an
      email alert containing only log entries in levels WARNING, ERROR and CRITICAL.
      To get also the INFO level in the emails just call the command from cron using verbosity=2 (-v2).
    - The logfile will allways log everything but DEBUG which is only visible when DEBUG is True.
    - When running from a terminal, no cron email involved, is the same, adjust what output you want to see with the
      verbosity level, and the logflie still will be logging everything.
    With this setup, a send command sending thousands of emails triggered by cron with the defaults in a production
    environment will not generate huge emails containing the delivery info entries for each email sent, those lines
    will be in the log file only and the email will hold only WARNING, ERROR and CRITICAL issues.
    """

    def handle(self, *args, **options):
        started_at = localtime()
        self.load_options(options)
        log = logging.getLogger(__name__)
        self.initlog(log, LOG_SUFFIX)

        print(f"\nDEBUG is {settings.DEBUG}, verbosity is {self.verbosity}")
        print("The lines you saw below should be consistent with the DEBUG and verbosity values\n")

        if settings.DEBUG:
            log.debug('debug line visible because DEBUG is True, no matter the verbosity level')
            log.info('info line visible because DEBUG is True, no matter the verbosity level')
            log.warning('warning line visible because DEBUG is True, no matter the verbosity level')
        else:
            log.debug('NOT visible because DEBUG is False')
            if not self.verbosity:
                log.info('NOT visible because verbosity < 1 (unless this is in the log file)')
                log.warning('NOT visible because verbosity < 1 (unless this is in the log file)')
            else:
                log.info('info line visible because verbosity >= 1, no matter the DEBUG value')
                log.warning('warning line visible because verbosity >= 1, no matter the DEBUG value')
        log.error('error line visible despite of DEBUG or verbosity value')
        log.critical('critical line visible despite of DEBUG or verbosity value')

        print(
            """
            Now check the log file: starting from %s lines you should see only 1 line for each of the all 4 levels of
            logging plus 1 line if DEBUG is True, run this to check it:

            tail %s
            """ % (
                started_at.strftime('%H:%M:%S'),
                settings.SENDNEWSLETTER_LOGFILE % (LOG_SUFFIX, started_at.strftime('%Y%m%d')),
            )
        )
