# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-22 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140, verbose_name='mensaje')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shouts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'ordering': ('-post_date',),
                'get_latest_by': 'post_date',
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
            },
        ),
    ]
