# Generated by Django 4.1.4 on 2024-05-12 07:55

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='image',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('photologue/watermarks'), verbose_name='image'),
        ),
    ]
